[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="a8f7c3d2e9b1f4a6c5d7e8f9g0h1i2j3"

[auth.auth0]
domain="dev-gebrmldtp31uiuna.us.auth0.com"
client_id="iE92Aay881SM5cemu05uQ72CeFjTDR0d"
client_secret="NG3d3_3NNfBVPjjnWKgi2PRqmhSx0spcVCEgl22o002Z6rFigabBvtmu0qBAZ9SQ"
server_metadata_url="https://dev-gebrmldtp31uiuna.us.auth0.com/.well-known/openid-configuration"
client_kwargs = {"prompt" = "login"}